name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-tests:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode 
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
    
    - name: Build and Test
      run: xcodebuild clean build test -project MyEssentialFeed/MyEssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
